spring:
  datasource:
    url: jdbc:postgresql://db:5432/test_ci_cd
    username: myuser
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true