spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_ci_cd
    username: myuser
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
