spring:
  datasource:
    url: jdbc:postgresql://db:5432/test_ci_cd
    username: myuser
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
