spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_ci_cd
    username: postgres
    password: 1313
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true